"use client";

import { useState, useEffect } from "react";
import { ArrowUpRight, ArrowRight, BookOpen, Check, ChevronRight, ChevronDown, CircleHelp, Compass, FileText, FlaskConical, FolderOpen, LayoutDashboard, ListTodo, Network, Plus, Radar, Search, Settings2, Sparkles, Bell, Layers3, Clock3 } from "lucide-react";
import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Toaster, toast } from "sonner";
import { initialPapers, initialTasks, Paper, Task, discoveries } from "./research-data";
import { PaperLibrary, Evidence, RadarView, Tasks, Reports } from "./workbench";

const navigation = [
  { id:"overview", name:"项目总览", icon:LayoutDashboard },
  { id:"papers", name:"文献中心", icon:BookOpen },
  { id:"evidence", name:"证据工作台", icon:Network },
  { id:"radar", name:"科研雷达", icon:Radar },
  { id:"tasks", name:"研究计划", icon:ListTodo },
  { id:"reports", name:"研究成果", icon:FileText },
];

export default function Home() {
  const [page, setPage] = useState("overview");
  const [papers,setPapers]=useState<Paper[]>(initialPapers);
  const [tasks,setTasks]=useState<Task[]>(initialTasks);
  const [selected,setSelected]=useState<number[]>([]);
  const [dismissed,setDismissed]=useState<number[]>([]);
  const [paused,setPaused]=useState(false);
  const [report,setReport]=useState("");
  const [isDemo,setIsDemo]=useState(true);
  const [confirmed,setConfirmed]=useState(false);
  const [project,setProject]=useState("大语言模型的可靠推理");
  const [goal,setGoal]=useState("如何让大语言模型的推理更准确、更可验证？");
  const [paperId,setPaperId]=useState<number|null>(null);
  const [modal,setModal]=useState<"project"|"import"|"direction"|"settings"|null>(null);
  const [assistant,setAssistant]=useState(false);
  const [message,setMessage]=useState("");
  const [answer,setAnswer]=useState("");
  const [formTitle,setFormTitle]=useState("");
  const [formGoal,setFormGoal]=useState("");
  const [formUrl,setFormUrl]=useState("");
  const currentPaper=papers.find(x=>x.id===paperId);
  const go=(id:string)=>{setPage(id);window.location.hash=id;window.scrollTo({top:0,behavior:"instant"});};
  useEffect(()=>{const sync=()=>{const v=window.location.hash.slice(1);if(navigation.some(n=>n.id===v))setPage(v);};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync)},[]);
  useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:"navigate_research_workspace",description:"Navigate to a research workspace view. Does not change research data.",inputSchema:{type:"object",properties:{view:{type:"string",enum:navigation.map(n=>n.id)}},required:["view"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const view=(input as {view?:string})?.view;if(!view||!navigation.some(n=>n.id===view))throw new Error("Unknown workspace view");go(view);await new Promise(resolve=>requestAnimationFrame(resolve));return{view};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
  function addTask(title:string,category:string,paperId?:number){if(tasks.some(t=>t.title===title&&!t.done)){toast.info("该任务已在研究计划中");return;}setTasks(prev=>[...prev,{id:Date.now(),title,category,done:false,paperId}]);toast.success("已加入研究计划",{action:{label:"查看",onClick:()=>go("tasks")}})}
  const shared={papers,setPapers,selected,setSelected,openPaper:setPaperId,go,tasks,setTasks,addTask,dismissed,setDismissed,project,goal,isDemo,confirmed,setConfirmed,paused,setPaused,report,setReport};
  function openModal(type:typeof modal){setFormTitle("");setFormGoal("");setFormUrl("");setModal(type)}
  function ask(question:string){setMessage(question);setAnswer(question.includes("比较")?"先选中两篇以上论文，按方法、数据与实验条件进行比较。证据工作台会保留待核查项，帮助你逐条回到原文。":question.includes("雷达")?"科研雷达将发现关联到研究问题。你可以查看影响、打开论文，或直接加入研究计划。当前为示例发现，尚未连接实时数据源。":"建议先精读过程监督的关键论文，再比较不同方法的实验条件。先核查材料，再形成项目判断。当前回复为交互演示，未连接大模型。");}
  return <SidebarProvider style={{"--sidebar-width":"232px"} as React.CSSProperties}>
    <Sidebar className="research-sidebar">
      <SidebarHeader><div className="brand"><div className="brand-mark"><FlaskConical size={22}/></div><span>SCI<span className="brand-light">Mate</span></span></div>
      <button className="workspace-switch" onClick={()=>openModal("project")}><div className="workspace-avatar">R</div><div><strong>我的研究空间</strong><small>Personal workspace</small></div><ChevronDown size={15}/></button></SidebarHeader>
      <SidebarContent><div className="nav-caption">工作空间</div><button className="all-projects" onClick={()=>openModal("project")}><FolderOpen size={18}/>项目与新建<ChevronRight size={15}/></button><div className="sidebar-divider"/><div className="nav-caption">当前项目</div><div className="project-name"><span className="project-dot"/>{project}</div><SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="nav-item" isActive={page===n.id} onClick={()=>go(n.id)}><n.icon size={18}/><span>{n.name}</span>{n.id==="radar"&&<span className="nav-count">{discoveries.length-dismissed.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent>
      <SidebarFooter><div className="sidebar-assistant"><Sparkles size={20}/><strong>你的科研助手</strong><p>随时讨论，继续探索。</p><button onClick={()=>setAssistant(true)}>开始对话 <ArrowUpRight size={15}/></button></div><button className="profile" onClick={()=>openModal("settings")}><span className="avatar">研</span><span>研究者<small>个人工作空间</small></span><Settings2 size={17}/></button></SidebarFooter>
    </Sidebar>
    <div className="app-main"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger/><span>我的项目</span><ChevronRight size={14}/><span>{project}</span></div><div className="topbar-actions"><span className="demo-label">交互原型 · 示例数据</span><button className="icon-btn" aria-label="科研动态" onClick={()=>go("radar")}><Bell size={19}/></button><span className="top-avatar">研</span></div></header>
    <main className="workspace"><div className="page-heading"><div><div className="eyebrow">RESEARCH WORKSPACE</div><h1>{navigation.find(n=>n.id===page)?.name}</h1><p>{project} <span className="inline-divider">/</span> 文献调研阶段</p></div><div className="heading-actions"><Button variant="outline" onClick={()=>openModal("import")}><Plus/>添加文献</Button><Button onClick={()=>setAssistant(true)}><Sparkles/>科研助手</Button></div></div>
    {page==="papers"&&<PaperLibrary {...shared}/>}
    {page==="evidence"&&<Evidence {...shared}/>}
    {page==="radar"&&<RadarView {...shared}/>}
    {page==="tasks"&&<Tasks {...shared}/>}
    {page==="reports"&&<Reports {...shared}/>}
    {page==="overview"&&!isDemo&&<section className="panel new-project-overview"><span className="tag blue-tag">新项目</span><h2>{goal}</h2><p>先添加核心文献，建立研究起点。</p><div><Button onClick={()=>openModal("import")}><Plus/>添加第一篇文献</Button><Button variant="outline" onClick={()=>go("papers")}>查看文献 · {papers.length} 篇</Button></div></section>}
    {page==="overview"&&isDemo&&<div className="overview-grid"><div className="main-column"><section className="focus-panel"><div className="section-kicker"><Compass size={17}/>当前研究问题<span className="tag light">探索中</span></div><h2 className="focus-question">{goal}</h2><div className="focus-footer"><div className="topic-tags"><span>推理机制</span><span>过程监督</span><span>自我纠错</span></div><button onClick={()=>openModal("direction")}>查看研究方向 <ArrowUpRight size={17}/></button></div></section>
    <div className="stats-row">{[{label:"收录文献",n:String(papers.filter(x=>x.saved).length),sub:`${papers.filter(x=>x.saved&&!x.read).length} 篇待精读`,icon:BookOpen,to:"papers"},{label:"研究证据",n:"3",sub:"示例比较 · 待核查",icon:Layers3,to:"evidence"},{label:"雷达发现",n:String(discoveries.length-dismissed.length),sub:"查看对课题的影响",icon:Radar,to:"radar"}].map(s=><button className="stat" key={s.label} onClick={()=>go(s.to)}><div><span>{s.label}</span><s.icon size={17}/></div><strong>{s.n}</strong><small>{s.sub}</small></button>)}</div>
    <section className="panel"><div className="section-heading"><h2>下一步行动 <span className="sub-count">{tasks.filter(x=>!x.done).length}</span></h2><button onClick={()=>go("tasks")}>全部计划 <ChevronRight size={15}/></button></div><div className="action-row"><span className="action-icon blue"><Network size={20}/></span><div><h3>比较三种推理增强方法</h3><p>从实验条件开始，找到结果差异的原因。</p><span className="mini-meta">3 篇文献 · 证据对比</span></div><Button variant="outline" onClick={()=>{setSelected([1,2,3]);go("evidence")}}>开始比较<ArrowRight/></Button></div><div className="action-row"><span className="action-icon purple"><BookOpen size={20}/></span><div><h3>精读过程监督的关键论文</h3><p>理解验证器的训练方式与适用边界。</p><span className="mini-meta">Let’s Verify Step by Step</span></div><Button variant="outline" onClick={()=>setPaperId(1)}>开始精读<ArrowRight/></Button></div></section>
    <section className="panel"><div className="section-heading"><h2>核心文献</h2><button onClick={()=>go("papers")}>文献中心 <ChevronRight size={15}/></button></div>{["Let's Verify Step by Step","Self-Consistency Improves Chain of Thought Reasoning","Tree of Thoughts: Deliberate Problem Solving"].map((t,i)=><button className="recent-paper" key={t} onClick={()=>setPaperId(i+1)}><div className="paper-icon"><FileText size={19}/></div><div><h3>{t}</h3><p>{["过程监督 · ICLR 2024","多路径推理 · ICLR 2023","搜索与规划 · NeurIPS 2023"][i]}</p></div><span className="tag">{i===0?"待精读":"已收录"}</span><ChevronRight size={16}/></button>)}</section></div>
    <aside className="right-column"><section className="panel radar-panel"><div className="section-heading"><h2><Radar size={18}/>科研雷达</h2><span className="status-dot">{paused?"已暂停":"演示"}</span></div><div className="radar-summary"><strong>{discoveries.length-dismissed.length}</strong><div>条值得关注的发现<small>最近一轮示例监测</small></div></div><div className="radar-item"><span className="tag blue-tag">研究进展</span><h3>过程监督：从答案正确到步骤可靠</h3><p>与你的「推理可验证性」问题相关。</p><button onClick={()=>go("radar")}>查看影响 <ArrowUpRight size={15}/></button></div><div className="radar-item"><span className="tag amber-tag">待核查</span><h3>自我纠错的有效条件仍需区分</h3><p>建议比较有无外部反馈的实验设置。</p><button onClick={()=>go("radar")}>查看证据 <ArrowUpRight size={15}/></button></div><button className="panel-bottom-link" onClick={()=>go("radar")}>查看全部发现<ArrowRight size={16}/></button></section><section className="panel progress-panel"><div className="section-heading"><h2>研究路径</h2><span className="mini-meta">阶段 02 / 05</span></div><ol className="research-path">{["明确研究问题","梳理文献与证据","设计研究方案","开展实验验证","整理研究成果"].map((x,i)=><li key={x} className={i===0?"done":i===1?"current":""}><span>{i===0?<Check size={13}/>:String(i+1).padStart(2,"0")}</span><div>{x}{i===1&&<small>当前阶段</small>}</div></li>)}</ol></section><div className="quiet-note"><Clock3 size={15}/><span>每一步研究，都有迹可循。</span></div></aside></div>}
    <footer className="workspace-footer"><span>SCIMate Research Studio</span><span>保持好奇，严谨求证。</span></footer></main></div>

    <Dialog open={modal!==null} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent className="research-dialog">
      <DialogTitle>{modal==="project"?"新建科研项目":modal==="import"?"添加文献":modal==="direction"?"研究方向":"工作空间"}</DialogTitle>
      <DialogDescription>{modal==="project"?"从一个研究问题开始。本原型在当前会话保存项目。":modal==="import"?"录入论文信息，加入当前项目。":modal==="direction"?"明确重点，让后续发现围绕课题展开。":"SCIMate Research Studio · 交互原型"}</DialogDescription>
      {modal==="project"&&<form className="research-form" onSubmit={e=>{e.preventDefault();if(!formTitle.trim()||!formGoal.trim())return;setIsDemo(false);setConfirmed(false);setProject(formTitle.trim());setGoal(formGoal.trim());setTasks([]);setPapers([]);setSelected([]);setDismissed([1,2,3]);setReport("");setModal(null);go("papers");toast.success("项目已创建，添加你的第一篇文献")}}><label>项目名称<Input value={formTitle} onChange={e=>setFormTitle(e.target.value)} placeholder="例如：大语言模型的可靠推理" required maxLength={80}/></label><label>研究问题<textarea value={formGoal} onChange={e=>setFormGoal(e.target.value)} placeholder="你希望研究什么问题？" required maxLength={240}/></label><div className="form-note">当前展示项目：{project}。新建后将切换到空白项目。</div><Button type="submit">创建并添加文献<ArrowRight/></Button></form>}
      {modal==="import"&&<form className="research-form" onSubmit={e=>{e.preventDefault();if(!formTitle.trim())return;setPapers(prev=>[...prev,{id:Date.now(),title:formTitle.trim(),url:formUrl,topic:"未分类",venue:"手动录入",year:"",summary:"等待阅读与提取。",method:"尚未提取",limitation:"尚未核查",saved:true,read:false}]);setModal(null);go("papers");toast.success("文献已加入项目")}}><label>论文标题<Input required value={formTitle} onChange={e=>setFormTitle(e.target.value)} placeholder="输入完整论文标题" maxLength={300}/></label><label>原文链接 <span className="muted">可选</span><Input type="url" value={formUrl} onChange={e=>setFormUrl(e.target.value)} placeholder="https://arxiv.org/abs/…" pattern="https?://.+"/></label><div className="form-note">本原型支持信息录入，全文解析需接入文献服务。</div><Button type="submit"><Plus/>加入项目</Button></form>}
      {modal==="direction"&&isDemo&&<div className="direction-content"><div className="direction-question">{goal}</div>{["推理机制","过程监督","自我纠错"].map((x,i)=><button key={x} onClick={()=>{setModal(null);go(i===1?"evidence":"papers")}}><span className="direction-number">0{i+1}</span><div><strong>{x}</strong><p>{["理解推理路径如何形成","探索中间步骤的验证方法","区分反馈来源与有效条件"][i]}</p></div><ArrowRight size={17}/></button>)}<Button variant="outline" onClick={()=>{setModal(null);setAssistant(true)}}><Sparkles/>讨论研究方向</Button></div>}
      {modal==="settings"&&<div className="settings-content"><p>当前数据仅用于体验操作流程，保存在本次页面会话中。</p><p>实时文献检索、持续监测、全文解析与 AI 对话尚未接入。</p><Button variant="outline" onClick={()=>{setIsDemo(true);setConfirmed(false);setPapers(initialPapers);setTasks(initialTasks);setSelected([]);setDismissed([]);setProject("大语言模型的可靠推理");setGoal("如何让大语言模型的推理更准确、更可验证？");setReport("");setModal(null);go("overview");toast.success("已恢复示例项目")}}>恢复示例项目</Button></div>}
    </DialogContent></Dialog>
    <Sheet open={paperId!==null} onOpenChange={v=>{if(!v)setPaperId(null)}}><SheetContent className="paper-sheet"><SheetHeader><div className="eyebrow">PAPER READER</div><SheetTitle>文献精读</SheetTitle><SheetDescription>结构化阅读 · 示例内容，待原文核查</SheetDescription></SheetHeader>{currentPaper&&<div className="reader-content"><div className="reader-meta"><span className="tag blue-tag">{currentPaper.topic}</span><span>{currentPaper.venue} {currentPaper.year}</span></div><h2>{currentPaper.title}</h2><div className="reader-toolbar">{currentPaper.url&&<Button variant="outline" asChild><a href={currentPaper.url} target="_blank" rel="noreferrer">打开原文<ArrowUpRight/></a></Button>}<Button variant="outline" onClick={()=>{setPapers(prev=>prev.map(x=>x.id===currentPaper.id?{...x,saved:!x.saved}:x))}}>{currentPaper.saved?<Check/>:<Plus/>}{currentPaper.saved?"已收录":"收录"}</Button></div><Tabs defaultValue="summary"><TabsList className="view-tabs"><TabsTrigger value="summary">核心内容</TabsTrigger><TabsTrigger value="project">与课题的关系</TabsTrigger><TabsTrigger value="resources">研究材料</TabsTrigger></TabsList><TabsContent value="summary"><div className="reader-block"><span>01 / 研究内容</span><p>{currentPaper.summary}</p></div><div className="reader-block"><span>02 / 核心方法</span><p>{currentPaper.method}</p></div><div className="reader-block"><span>03 / 核查边界</span><p>{currentPaper.limitation}</p></div><div className="source-note">当前是演示知识卡片，未解析全文或提取实验数据。请通过原文链接核查。</div></TabsContent><TabsContent value="project"><div className="reader-block"><span>当前研究问题</span><p>{goal}</p></div><div className="reader-block"><span>建议核查</span><p>记录方法的反馈来源、评价条件与计算成本，再判断是否适用于你的研究问题。</p></div><Button variant="outline" onClick={()=>addTask(`核查：${currentPaper.title}`,"文献精读",currentPaper.id)}>加入研究计划<Plus/></Button></TabsContent><TabsContent value="resources"><div className="reader-block"><span>材料清单</span><p>原文链接：{currentPaper.url?"已关联":"尚未添加"}</p><p>代码与数据集：尚未核查</p><p>实验环境：尚未提取</p></div><Button variant="outline" onClick={()=>addTask(`整理代码与数据：${currentPaper.title}`,"研究准备",currentPaper.id)}>创建材料准备任务<Plus/></Button></TabsContent></Tabs><div className="reader-bottom"><Button onClick={()=>{setPapers(prev=>prev.map(x=>x.id===currentPaper.id?{...x,read:!x.read}:x));toast.success(currentPaper.read?"已标记为待阅读":"已标记为已读")}}>{currentPaper.read?<Check/>:<BookOpen/>}{currentPaper.read?"已读 · 标记为未读":"标记为已读"}</Button><Button variant="outline" onClick={()=>{setSelected(prev=>prev.includes(currentPaper.id)?prev:[...prev,currentPaper.id]);setPaperId(null);go("papers");toast.info("已选中该论文，请再选择一篇进行比较")}}>加入对比<Network/></Button></div></div>}</SheetContent></Sheet>
    <Sheet open={assistant} onOpenChange={setAssistant}><SheetContent className="assistant-sheet"><SheetHeader><div className="assistant-emblem"><Sparkles size={24}/></div><SheetTitle>科研助手</SheetTitle><SheetDescription>围绕当前课题，继续下一步。</SheetDescription></SheetHeader><div className="assistant-context"><span>当前项目</span><strong>{project}</strong></div><div className="assistant-body"><p>你想先做什么？</p>{["我下一步应该做什么？","帮我比较核心论文","解释雷达发现的影响"].map(x=><button className="suggestion" key={x} onClick={()=>ask(x)}>{x}<ArrowUpRight size={16}/></button>)}{answer&&<div className="assistant-response" aria-live="polite"><span className="tag">演示回复</span><p>{answer}</p><Button variant="outline" onClick={()=>{go(message.includes("比较")?"evidence":message.includes("雷达")?"radar":"tasks");setAssistant(false)}}>打开工作台<ArrowRight/></Button></div>}</div><form className="assistant-input" onSubmit={e=>{e.preventDefault();if(message.trim())ask(message.trim())}}><label htmlFor="assistant-message">补充你的研究需求</label><div><Input id="assistant-message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="例如：比较实验条件" maxLength={500}/><Button type="submit" size="icon" disabled={!message.trim()} aria-label="发送"><ArrowRight/></Button></div><small>交互演示 · 尚未连接大模型</small></form></SheetContent></Sheet>
    <Toaster position="bottom-right" richColors closeButton/>
  </SidebarProvider>;
}
