"use client";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, Check, CheckCheck, ChevronRight, Download, ExternalLink, FileText, Filter, ListTodo, Loader2, Network, Pause, Play, Plus, Radar, Search, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from "@/components/ui/table";
import { toast } from "sonner";
import { Paper, Task, discoveries } from "./research-data";

type Props={papers:Paper[];setPapers:React.Dispatch<React.SetStateAction<Paper[]>>;selected:number[];setSelected:React.Dispatch<React.SetStateAction<number[]>>;openPaper:(id:number)=>void;go:(page:string)=>void;tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;addTask:(title:string,category:string,paperId?:number)=>void;dismissed:number[];setDismissed:React.Dispatch<React.SetStateAction<number[]>>;project:string;goal:string;isDemo:boolean;confirmed:boolean;setConfirmed:React.Dispatch<React.SetStateAction<boolean>>;paused:boolean;setPaused:React.Dispatch<React.SetStateAction<boolean>>;report:string;setReport:React.Dispatch<React.SetStateAction<string>>};
export function PaperLibrary(p:Props){
 const [query,setQuery]=useState("");const [tab,setTab]=useState("saved");const [topic,setTopic]=useState("全部方向");
 const filtered=p.papers.filter(x=>(tab==="all"||tab==="saved"&&x.saved||tab==="unread"&&x.saved&&!x.read)&&(topic==="全部方向"||x.topic===topic)&&`${x.title} ${x.topic} ${x.method}`.toLowerCase().includes(query.toLowerCase()));
 return <><Tabs value={tab} onValueChange={setTab}><div className="library-toolbar"><TabsList className="view-tabs"><TabsTrigger value="saved">已收录 {p.papers.filter(x=>x.saved).length}</TabsTrigger><TabsTrigger value="unread">待精读</TabsTrigger><TabsTrigger value="all">发现文献</TabsTrigger></TabsList><div className="search-field"><Search size={17}/><Input aria-label="搜索示例文献" placeholder="搜索标题、方向或方法" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="filter-row"><span><Filter size={15}/>研究方向</span>{["全部方向",...Array.from(new Set(p.papers.map(x=>x.topic)))].map(x=><button key={x} className={topic===x?"filter-chip active":"filter-chip"} onClick={()=>setTopic(x)}>{x}</button>)}</div><div className="panel paper-list"><div className="list-caption"><span>{filtered.length} 篇文献</span><span>示例资料集 · 检索仅限当前列表</span></div>{filtered.length===0?<Empty text="没有找到匹配的文献" action="清除筛选" onClick={()=>{setQuery("");setTopic("全部方向");setTab("all")}}/>:filtered.map(paper=><article className="library-paper" key={paper.id}><Checkbox aria-label={`选择 ${paper.title}`} checked={p.selected.includes(paper.id)} onCheckedChange={v=>p.setSelected(prev=>v?[...prev,paper.id]:prev.filter(x=>x!==paper.id))}/><div className="library-paper-main"><div className="paper-metadata"><span className="tag blue-tag">{paper.topic}</span><span>{paper.venue} {paper.year}</span>{paper.read&&<span className="read-status"><Check size={13}/>已读</span>}</div><button className="paper-title" onClick={()=>p.openPaper(paper.id)}>{paper.title}</button><p>{paper.summary}</p><div className="paper-links"><a href={paper.url||undefined} target="_blank" rel="noreferrer" aria-disabled={!paper.url}>{paper.url?<>原文<ExternalLink size={12}/></>:"手动录入 · 未连接原文"}</a><span>{paper.read?"已核阅示例卡片":"待核阅"}</span></div></div><div className="paper-actions"><Button variant="outline" onClick={()=>p.openPaper(paper.id)}><BookOpen/>精读</Button><button className={paper.saved?"saved-label":"save-link"} onClick={()=>{p.setPapers(prev=>prev.map(x=>x.id===paper.id?{...x,saved:!x.saved}:x));toast.success(paper.saved?"已移出收录列表":"已收录到项目")}}>{paper.saved?<><Check size={14}/>已收录</>:<><Plus size={14}/>收录</>}</button></div></article>)}</div></Tabs>{p.selected.length>0&&<div className="selection-bar"><span>已选择 <strong>{p.selected.length}</strong> 篇</span><button onClick={()=>p.setSelected([])}>取消选择</button><Button disabled={p.selected.length<2} onClick={()=>p.go("evidence")}><Network/>比较文献<ArrowRight/></Button></div>}</>;
}
export function Evidence(p:Props){
 const chosen=p.papers.filter(x=>p.selected.includes(x.id));const list=chosen.length>=2?chosen:p.papers.filter(x=>x.saved).slice(0,3);const {confirmed,setConfirmed}=p;
 return <><div className="evidence-banner"><span className="action-icon blue"><Network size={23}/></span><div><h2>{p.goal}</h2><p>按相同维度比较，逐条回到原文核查。</p></div><Button variant="outline" onClick={()=>p.go("papers")}>选择文献</Button></div><div className="section-heading standalone"><h2>方法比较 <span className="sub-count">{list.length} 篇</span></h2><span className="tag amber-tag">示例提取 · 待核查</span></div>{list.length<2?<div className="panel"><Empty text="先收录至少两篇文献，开始比较" action="前往文献中心" onClick={()=>p.go("papers")}/></div>:<div className="panel evidence-table"><Table><TableHeader><TableRow><TableHead className="dimension-col">比较维度</TableHead>{list.map(x=><TableHead key={x.id}><button onClick={()=>p.openPaper(x.id)}>{x.title}<ArrowUpRight size={15}/></button><small>{x.venue} · {x.year}</small></TableHead>)}</TableRow></TableHeader><TableBody>{[{name:"研究方向",key:"topic"},{name:"核心方法",key:"method"},{name:"研究内容",key:"summary"},{name:"待核查边界",key:"limitation"}].map(row=><TableRow key={row.key}><TableCell className="dimension-col">{row.name}</TableCell>{list.map(x=><TableCell key={x.id}><button className="evidence-cell" onClick={()=>p.openPaper(x.id)}>{x[row.key as keyof Paper]}<span>查看论文 <ArrowUpRight size={12}/></span></button></TableCell>)}</TableRow>)}<TableRow><TableCell className="dimension-col">实验结果</TableCell>{list.map(x=><TableCell key={x.id}><span className="muted">尚未提取</span><p className="cell-note">请核查原文数据与实验条件</p></TableCell>)}</TableRow></TableBody></Table></div>}{p.isDemo&&<div className="evidence-bottom"><section className="panel insight-panel"><div className="section-heading"><h2><Sparkles size={18}/>研究提示</h2><span className="tag">AI 示例</span></div><div className="panel-body"><h3>先对齐条件，再比较效果</h3><p>将模型、数据集、采样预算和反馈来源加入核查清单。当前材料不足以直接判断哪种方法更优。</p><Button variant="outline" onClick={()=>p.addTask("核查对比论文的模型、数据集与推理预算","证据核查")}>加入核查计划<Plus/></Button></div></section><section className="panel insight-panel"><div className="section-heading"><h2>项目判断</h2><span className={confirmed?"tag green-tag":"tag amber-tag"}>{confirmed?"已记录":"待确认"}</span></div><div className="panel-body"><h3>将过程验证作为候选研究路线</h3><p>这是一条探索假设，尚不能作为领域共识或研究结论。</p><Button variant="outline" onClick={()=>{setConfirmed(!confirmed);toast.success(confirmed?"已恢复为待确认":"已记录为项目候选路线")}}>{confirmed?<Check/>:<Plus/>}{confirmed?"已纳入候选路线":"纳入候选路线"}</Button></div></section></div>}</>;
}
export function RadarView(p:Props){const[filter,setFilter]=useState("全部发现");const[scanning,setScanning]=useState(false);const[scanned,setScanned]=useState(false);const list=discoveries.filter(x=>!p.dismissed.includes(x.id)&&(filter==="全部发现"||x.type===filter));
 return <><div className="radar-control panel"><div className="radar-control-icon"><Radar size={31}/></div><div><h2>{p.paused?"监测已暂停":"关注你的研究方向"}</h2><p>{p.isDemo?"过程监督 · 推理机制 · 自我纠错":p.goal}</p><small>{scanned?"示例检查完成 · 没有更多发现":"演示模式 · 尚未连接实时学术数据源"}</small></div><div className="radar-control-actions"><Button variant="outline" onClick={()=>p.setPaused(!p.paused)}>{p.paused?<Play/>:<Pause/>}{p.paused?"恢复监测":"暂停监测"}</Button><Button disabled={scanning||p.paused} onClick={()=>{setScanning(true);setTimeout(()=>{setScanning(false);setScanned(true);toast.info("示例检查完成。实时检索需接入学术数据源。");},900)}}>{scanning?<Loader2 className="spin"/>:<Radar/>}{scanning?"检查中":"演示检查"}</Button></div></div><div className="filter-row radar-filters">{["全部发现","研究进展","待核查","研究资源"].map(x=><button key={x} className={filter===x?"filter-chip active":"filter-chip"} onClick={()=>setFilter(x)}>{x}</button>)}<span className="muted">{list.length} 条发现</span></div><div className="discovery-list">{!list.length?<div className="panel"><Empty text="当前没有待处理的发现" action={p.isDemo?"恢复示例发现":undefined} onClick={()=>{p.setDismissed([]);setFilter("全部发现")}}/></div>:list.map((x,i)=><article className="panel discovery" key={x.id}><div className="discovery-top"><span className={`tag ${x.type==="待核查"?"amber-tag":"blue-tag"}`}>{x.type}</span><span className="mini-meta">示例信号 {String(x.id).padStart(2,"0")}</span></div><h2>{x.title}</h2><p>{x.description}</p><div className="impact"><span>对课题的影响</span><p>{x.impact}</p></div><div className="discovery-bottom"><span className="relevance"><span/>{x.tag}</span><div><button className="text-button" onClick={()=>p.setDismissed(prev=>[...prev,x.id])}>忽略</button><Button variant="outline" onClick={()=>p.openPaper(x.paperId)}>查看论文<ArrowUpRight/></Button><Button onClick={()=>p.addTask(x.title,x.type,x.paperId)}>加入计划<Plus/></Button></div></div></article>)}</div></>;
}
export function Tasks(p:Props){const[title,setTitle]=useState("");const[tab,setTab]=useState("todo");const list=p.tasks.filter(x=>tab==="done"?x.done:!x.done);return <><form className="task-add panel" onSubmit={e=>{e.preventDefault();if(title.trim()){p.addTask(title.trim(),"自定义任务");setTitle("")}}}><Plus size={20}/><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="添加下一步研究任务" aria-label="新任务名称" maxLength={160}/><Button type="submit" disabled={!title.trim()}>添加任务</Button></form><Tabs value={tab} onValueChange={setTab}><TabsList className="view-tabs"><TabsTrigger value="todo">待完成 {p.tasks.filter(x=>!x.done).length}</TabsTrigger><TabsTrigger value="done">已完成 {p.tasks.filter(x=>x.done).length}</TabsTrigger></TabsList><div className="panel task-list">{list.length?list.map(x=><div className="task-item" key={x.id}><Checkbox checked={x.done} aria-label={`${x.done?"恢复":"完成"}任务：${x.title}`} onCheckedChange={checked=>p.setTasks(prev=>prev.map(t=>t.id===x.id?{...t,done:!!checked}:t))}/><div><h3 className={x.done?"completed":""}>{x.title}</h3><span className="tag">{x.category}</span></div>{!x.done&&<Button variant="ghost" onClick={()=>x.paperId?p.openPaper(x.paperId):p.go(x.category==="证据对比"||x.category==="证据核查"?"evidence":"papers")}>打开材料<ArrowRight/></Button>}</div>):<Empty text={tab==="done"?"还没有完成的任务":"当前计划已完成"}/>}</div></Tabs><div className="subtle-help"><CheckCheck size={16}/>完成的任务会保留在项目记录中。本次原型数据仅保留在当前页面会话。</div></>}
export function Reports(p:Props){const[busy,setBusy]=useState(false);function generate(){setBusy(true);setTimeout(()=>{p.setReport(`# ${p.project}\n\n## 阶段研究简报\n\n本简报由当前示例项目数据整理，尚未接入模型，不代表已验证的科研结论。\n\n### 文献积累\n\n${p.papers.filter(x=>x.saved).map(x=>`- ${x.title}（${x.venue} ${x.year}）\n  ${x.url}`).join("\n")}\n\n### 当前重点\n\n${p.isDemo?"比较推理机制、过程监督与自我纠错的适用条件。对齐模型、数据集和推理预算后再评估结果。":p.goal}\n\n### 下一步研究\n\n${p.tasks.filter(x=>!x.done).map(x=>`- ${x.title}`).join("\n")}\n\n### 核查说明\n\n论文原文需要进一步核查；本原型没有提取实验数值，也未执行任何实验。`);setBusy(false)},650)}function download(){const url=URL.createObjectURL(new Blob([p.report],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="SCIMate-阶段研究简报.md";a.click();URL.revokeObjectURL(url)}return <><div className="report-hero panel"><div className="report-symbol"><FileText size={33}/></div><div><h2>把研究积累，整理成阶段成果</h2><p>汇总已收录文献、当前重点与下一步计划。</p></div><Button disabled={busy} onClick={generate}>{busy?<Loader2 className="spin"/>:<Sparkles/>}{busy?"整理中":p.report?"更新简报":"生成阶段简报"}</Button></div>{p.report?<section className="panel report-document"><div className="section-heading"><h2>阶段研究简报 <span className="tag">示例汇总</span></h2><Button variant="outline" onClick={download}><Download/>导出 Markdown</Button></div><textarea aria-label="编辑阶段研究简报" value={p.report} onChange={e=>p.setReport(e.target.value)}/></section>:<section className="panel"><Empty text="还没有研究成果"/><div className="empty-note">点击「生成阶段简报」，整理当前项目材料。</div></section>}</>}
export function Empty({text,action,onClick}:{text:string;action?:string;onClick?:()=>void}){return <div className="empty-state"><FolderIcon/><h3>{text}</h3>{action&&<Button variant="outline" onClick={onClick}>{action}</Button>}</div>}
function FolderIcon(){return <BookOpen size={28} strokeWidth={1.3}/>}
